spring.application.name=secure-auth-backend
server.port=${PORT:8080}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/authdb}
spring.data.mongodb.auto-index-creation=true

# JWT (REQUIRED in prod via APP_JWT_SECRET env var)
app.jwt.secret=${APP_JWT_SECRET:CHANGE_ME_dev_only_secret_min_32_chars_long_xyz}
app.jwt.expiration-hours=${APP_JWT_EXPIRATION_HOURS:24}

